# cloudbuild.yaml

steps:
  - id: list files
    name: ubuntu
    script: ls -laRth
  - id: 'terraform init'
    name: 'hashicorp/terraform:1..90'
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.9.0'
    script: terraform plan
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.9.0'
    script: terraform apply