# cloudbuild.yaml

steps:
  - id: list files
    name: ubuntu
    script: ls -laRth
  - id: 'terraform init'
    dir: ./infrastructure/terraform
    name: 'hashicorp/terraform:1..90'
    script: terraform init
  - id: 'terraform plan'
    dir: ./infrastructure/terraform
    name: 'hashicorp/terraform:1.9.0'
    script: terraform plan
  - id: 'terraform apply'
    dir: ./infrastructure/terraform
    name: 'hashicorp/terraform:1.9.0'
    script: terraform apply --auto-approve

options:
  logging: CLOUD_LOGGING_ONLY